### ISSUE TITLE
Animations? Images?

### ISSUE THREAD

**Issue by utdrmac** [faqy003/OniMod-Stairs#3]
Where is the `anim` folder with all the pictures/assets? Can't compile this and load without the pictures.

**Comment by utdrmac** [comment]
@faqy003 ^^

**Comment by faqy003** [comment]
They're shipping with release vesion
https://steamcommunity.com/sharedfiles/filedetails/?id=2012810337

**Comment by utdrmac** [comment]
Could you include them in github, please? I'd like to try some modifications. This is the only of my 10 mods that doesn't have all necessary content on github.

**Comment by faqy003** [comment]
I just upload them .
