### ISSUE TITLE
Crashing when click on Scaffolding, after today update.

### ISSUE THREAD

**Issue by SpardaCR** [faqy003/OniMod-Stairs#9]
ArgumentException: CreateExosuitRegion is not bound in GameInputBindings

GameUtil.ActionToBinding (Action action) (at <78df64db9f81466a987bb95b601e9104>:0)
GameUtil.GetActionString (Action action) (at <78df64db9f81466a987bb95b601e9104>:0)
GameUtil.GetHotkeyString (Action action) (at <78df64db9f81466a987bb95b601e9104>:0)
GameUtil.ReplaceHotkeyString (System.String template, Action action) (at <78df64db9f81466a987bb95b601e9104>:0)
KIconButtonMenu+ButtonInfo.GetTooltipText () (at <78df64db9f81466a987bb95b601e9104>:0)
KIconButtonMenu.RefreshButtons () (at <78df64db9f81466a987bb95b601e9104>:0)
KIconButtonMenu.SetButtons (System.Collections.Generic.IList`1[T] buttons) (at <78df64db9f81466a987bb95b601e9104>:0)
UserMenuScreen.Refresh (UnityEngine.GameObject go) (at <78df64db9f81466a987bb95b601e9104>:0)
RootMenu.Refresh () (at <78df64db9f81466a987bb95b601e9104>:0)
RootMenu.OnSelectObject (System.Object data) (at <78df64db9f81466a987bb95b601e9104>:0)
EventSystem.Trigger (UnityEngine.GameObject go, System.Int32 hash, System.Object data) (at <addcb9bdd73c454398a14811a9320244>:0)
KMonoBehaviour.Trigger (System.Int32 hash, System.Object data) (at <addcb9bdd73c454398a14811a9320244>:0)
(wrapper dynamic-method) SelectTool.SelectTool.Select_Patch1(SelectTool,KSelectable,bool)
SelectTool.OnLeftClickDown (UnityEngine.Vector3 cursor_pos) (at <78df64db9f81466a987bb95b601e9104>:0)
PlayerController.OnKeyDown (KButtonEvent e) (at <78df64db9f81466a987bb95b601e9104>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <addcb9bdd73c454398a14811a9320244>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <addcb9bdd73c454398a14811a9320244>:0)
KInputHandler.HandleEvent (KInputEvent e) (at <addcb9bdd73c454398a14811a9320244>:0)
KInputController.Dispatch () (at <addcb9bdd73c454398a14811a9320244>:0)
KInputManager.Dispatch () (at <addcb9bdd73c454398a14811a9320244>:0)
KInputManager.Update () (at <addcb9bdd73c454398a14811a9320244>:0)
GameInputManager.Update () (at <addcb9bdd73c454398a14811a9320244>:0)
Global.Update () (at <78df64db9f81466a987bb95b601e9104>:0)

Build: U45-544519-S

**Comment by faqy003** [comment]
Already fixed.
